### ISSUE TITLE
Transition arm over to libhal instead of sjsu-dev2

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#10]
This is a huge project. The drive is pretty much done but needs to be further tested. Use the current drive with libhal to help with this conversion.

**Comment by starphys** [comment]
Created [a branch](https://github.com/SJSURoboticsTeam/urc-control-system-2023/tree/arm-to-libhal/) with the first pass at migrating arm. Once that builds and runs on hardware, the next steps will be to rebuild all of the desired functionality, including rr9 controls, homing with mpus, and thorough command validation.

**Comment by Coreyboy1820** [comment]
Done
