### ISSUE TITLE
Pressure Pump driver: implement way to find out if container is fully pressurized

### ISSUE THREAD

**Issue by PhazonicRidley** [SJSURoboticsTeam/urc-control-system-2023#23]
After locking what we are using as a pressure sensor. We need a way to figure out way to detect if a container is pressurized. I'd assume this would be either max voltage (3.3V) detected from ADC OR the sensor would have a digital pin to do this for us.

**Comment by Coreyboy1820** [comment]
This is not part of the pump driver and is implemented in a separate file.
