### ISSUE TITLE
Pressure sensor driver

### ISSUE THREAD

**Issue by PhazonicRidley** [SJSURoboticsTeam/urc-control-system-2023#24]

**Comment by william-green** [comment]
The sparkfun breakout board contains the BME680. The BME680 contains many sensors. We are only interested in the pressure sensor. The BME680 datasheet is below.

Communication between lpc chipset and the breakout board occurs over I2C.

BME680 Data Sheet. Pressure sensor register information appears to be on page 30.
[bst-bme680-ds001.pdf](https://github.com/SJSURoboticsTeam/urc-control-system-2023/files/11780325/bst-bme680-ds001.pdf)

Sparkfun Breakout Board Arduino Library Source Code
[Zanshin_BME680.zip](https://github.com/SJSURoboticsTeam/urc-control-system-2023/files/11780328/Zanshin_BME680.zip)
