### ISSUE TITLE
Servo Driver

### ISSUE THREAD

**Issue by PhazonicRidley** [SJSURoboticsTeam/urc-control-system-2023#25]

**Comment by a3has** [comment]
270 Servo: 
Running current: 3000mA/6.0V, 3500mA/7.4V, 3800mA/8.4V
Control: PWM
Note: Will be powered with 12v, limit pwm to 50%

360 Servo: 
5V
Control: PWM. 
Note: Will be powered with ?V, limit pwm to ?%

**Comment by Coreyboy1820** [comment]
Not needed. Just needed the specs for each servo.
