### ISSUE TITLE
CO2 sensor driver

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#5]
The science team needs a driver for the following co2 sensor. https://cdn-learn.adafruit.com/downloads/pdf/adafruit-scd-40-and-scd-41.pdf

**Comment by PhazonicRidley** [comment]
In the process of finding a new CO2 sensor

**Comment by Viha123** [comment]
Datasheet: https://cdn.sparkfun.com/assets/d/4/9/a/d/Sensirion_CO2_Sensors_SCD4x_Datasheet.pdf

**Comment by Coreyboy1820** [comment]
Finished tonight.

**Comment by kammce** [comment]
@Coreyboy1820 make sure to associate the PR that fixed this. Otherwise its hard to track what actually fixed this. You'd need to use the dates in which things were merged and this comment was made to figure it out.

**Comment by kammce** [comment]
Resolved by #55 and #53. 

☝🏾 like so 😄
