### ISSUE TITLE
Dosing pump driver

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#6]
The science bot has an injector for the different chemicals, so we need a driver, heres a link but it may change: https://www.amazon.com/Peristaltic-Dosing-Miniature-Self-Priming-plug-6V/dp/B07T2ZVNVY/ref=sr_1_2?keywords=peristaltic+6v+pump&qid=1674017734&sr=8-2

**Comment by Coreyboy1820** [comment]
Dosing pump is finalized, the link is to the correct version.

**Comment by PhazonicRidley** [comment]
Awaiting electrical's motor controller board and libhal's lpc4078 pwm API implementation.

See: [This Commit](https://github.com/SJSURoboticsTeam/urc-control-system-2023/commit/243194ca43031942f345c71951b8bdd62b41ad3e)

**Comment by PhazonicRidley** [comment]
Need to certain specific information about controller board. Need PWM duty cycle, max frequency, frequency range

**Comment by william-green** [comment]
This appears to be the datasheet for this pump.
[ROB-10398_eng_tds.pdf](https://github.com/SJSURoboticsTeam/urc-control-system-2023/files/10775197/ROB-10398_eng_tds.pdf)

**Comment by william-green** [comment]
ETA for board for pump system is Monday.

PWM from Dev2 will control the mosfet board for all the pumps. Basically, the dev2 board cannot output high enough current to drive the motor pumps. Therefore, the mosfet board will handle power to the pump motors. PWM output from the dev2 board will turn the mosfets off and on controlling the motors in the pumping systems.

**Comment by william-green** [comment]
Overview of the science robot: samples and pump mechanisms.
![IMG_3988](https://user-images.githubusercontent.com/19770167/219904241-76ce2a46-2509-423f-96b0-ec1f9ce3ca9a.png)

**Comment by william-green** [comment]
Running low on PCA. Ordered 5 more PCA boards eta 2-19-23.

**Comment by william-green** [comment]
Here is an overview of the pump system. For development/prototyping, we're using a PCA board but, in the final product, the PCA chip is integrated into the science board.
![PXL_20230219_005255242](https://user-images.githubusercontent.com/19770167/219906270-6e4d0ef5-e52b-44f4-8d80-e80de2ddd0e3.jpg)
