### ISSUE TITLE
Fix Seal Servo

### ISSUE THREAD

**Issue by PhazonicRidley** [SJSURoboticsTeam/urc-control-system-2023#68]
The pwm values given for for "Open" (set servo to 90 degrees) and "Close" (set servo to 0 degrees) are not what they should be. They should be corrected. 

This servo is supposed to be a 270 servo however while testing, we were able to let it rotate 360 degrees. It should not have been doing that or even able to do that. Datasheet is to be found.

**Comment by Viha123** [comment]
Datasheet: https://betuservo.com/prosdetail_4593291.html
1. factor = Convert Hz to milliseconds (1/hz)*1000
2. divide 500 microseconds (0.5ms/factor) (lower bound)
3. 2500 microseconds (2.5/factor) upper bound

**Comment by Viha123** [comment]
Fixed in branch: seal-servo-demo
