### ISSUE TITLE
Air pump driver

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#7]
The science team needs an air pump and it needs a driver, heres the amazon link for it: https://abra-electronics.com/electromechanical/other-motors/d028b-airpo-vacuum-pump-12v-d028b.html

**Comment by Coreyboy1820** [comment]
Air pump is finalized, the link is to the correct version.

**Comment by PhazonicRidley** [comment]
Awaiting electrical's motor controller board and libhal's lpc4078 pwm API implementation.

See: [This Commit](https://github.com/SJSURoboticsTeam/urc-control-system-2023/commit/243194ca43031942f345c71951b8bdd62b41ad3e)

**Comment by PhazonicRidley** [comment]
Need to certain specific information about controller board. Need PWM duty cycle, max frequency, frequency range

**Comment by Pinyiyeh** [comment]
The PWM frequency for the air pump and dosing pump should be 32kHz.

**Comment by kammce** [comment]
The maximum frequency of the PCA PWM generators is 1.56kHz, so 32kHz is not achievable. @Pinyiyeh

**Comment by Pinyiyeh** [comment]
My mistake. We state the frequency required to drive the pump motor on the schematic. 
The air pump and dosing pump motor should be driven at 1.5kHz.

**Comment by kammce** [comment]
No no, not your mistake, just unfortunate that we cannot achieve higher frequencies.

**Comment by Pinyiyeh** [comment]
Yeah, 1.5kHz is too low for a DC motor.

**Comment by kammce** [comment]
Yeah thats why I brought it up during the board review. You can run them at 1.5kHz, but when you are stepping them down at that frequency it can be very problematic.
