### ISSUE TITLE
Hall effect driver

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#8]
The science team needs a driver for the hall effect, research this and create a driver for it. https://www.amazon.com/gp/product/B07QS6PN3B/ref=ox_sc_act_title_1?smid=A34K5WF5Z9R33P&psc=1

**Comment by Coreyboy1820** [comment]
This is really just creating a demo to see how it works and if it even does work.

**Comment by Coreyboy1820** [comment]
Hall effect sensor is finalized, this is the correct sensor.

**Comment by william-green** [comment]
@Coreyboy1820 I made a pull request for a working demo. Let me know what the next steps are. Should I make a wrapper class for abstraction purposes? Thanks

Here is the circuit schematic used.
![PXL_20230211_231133446 MP](https://user-images.githubusercontent.com/19770167/218286705-54459b55-be68-4af0-a33d-1a75a141228f.jpg)

**Comment by william-green** [comment]
Finished.
