### ISSUE TITLE
Add `sjsu::urc_mission_control` interface

### ISSUE THREAD

**Issue by kammce** [SJSURoboticsTeam/urc-control-system-2023#82]
This will allow applications to eliminate the coupling to specific port or technology for communication. This way the applications do not need to depend on or use specifically the esp8266 or a serial port for getting commands. 

The interface should return the mission control command and NOT return a string that then must be parsed. The implementation handles the lower level details of communicating with mission control. 

There may need to a mission control interface for each sub system, but there may be a possible way to do this with a single interface scheme, maybe using `std::variant`.

**Comment by Coreyboy1820** [comment]
@50xp50 This task is the one I was talking about.

**Comment by Viha123** [comment]
@Coreyboy1820 has done this
