### ISSUE TITLE
MPU driver for libhal

### ISSUE THREAD

**Issue by Coreyboy1820** [SJSURoboticsTeam/urc-control-system-2023#9]
The mpu for libhal hasn't been filled out yet and we need this in order to home the arm. Get this done asap for homing.

**Comment by FluffyFTW** [comment]
I aim to get the first set of code imported by 2/3/23 and aim to debug and finish testing it by 2/10/23* (This date is subject to change as problems arise, they will arise)

**Comment by FluffyFTW** [comment]
https://github.com/libhal/libhal-mpu
1.0.0 is released as of 2/18/23
